In [38]:
# Import Dependencies
import pandas as pd

In [39]:
state_avg_csv = "Resources/state_avg.csv"
state_totals_csv = "Resources/state_totals.csv"

In [40]:
state_avg_df = pd.read_csv(state_avg_csv)
state_totals_df = pd.read_csv(state_totals_csv)

In [41]:
state_avg_df.head()

,Year,State,Average Median Age by County,Average Household Income by County,Average Per Capita Income by County
0,2016,Alabama,40.250746,38834.925373,21232.746269
1,2016,Alaska,36.624138,64801.655172,31052.103448
2,2016,Arizona,39.613333,44166.533333,21786.333333
3,2016,Arkansas,41.140000,37503.720000,20591.666667
4,2016,California,39.281034,58091.241379,29025.793103

In [42]:
state_totals_df.head()

,Year,State,Total Population,Total Employed Civilians,Total Unemployed Civilians,Total People in the Military,Total Population in Poverty
0,2016,Alabama,4841164,2042025.0,184479.0,12150.0,868666.0
1,2016,Alaska,736855,353954.0,30139.0,16382.0,72826.0
2,2016,Arizona,6728577,2879372.0,249972.0,17373.0,1165636.0
3,2016,Arkansas,2968472,1266552.0,93190.0,4445.0,542431.0
4,2016,California,38654206,17577142.0,1683726.0,130452.0,6004257.0

In [43]:
# Merge the two DataFrames together based on the Year and State they share
df_merged = pd.merge(state_avg_df, state_totals_df, on=["Year", "State"])

df_merged.head()

,Year,State,Average Median Age by County,Average Household Income by County,Average Per Capita Income by County,Total Population,Total Employed Civilians,Total Unemployed Civilians,Total People in the Military,Total Population in Poverty
0,2016,Alabama,40.250746,38834.925373,21232.746269,4841164,2042025.0,184479.0,12150.0,868666.0
1,2016,Alaska,36.624138,64801.655172,31052.103448,736855,353954.0,30139.0,16382.0,72826.0
2,2016,Arizona,39.613333,44166.533333,21786.333333,6728577,2879372.0,249972.0,17373.0,1165636.0
3,2016,Arkansas,41.140000,37503.720000,20591.666667,2968472,1266552.0,93190.0,4445.0,542431.0
4,2016,California,39.281034,58091.241379,29025.793103,38654206,17577142.0,1683726.0,130452.0,6004257.0

In [44]:
# Create a DataFrame that filters the data on only 2019
df_merged.dtypes

df = df_merged[df_merged["Year"] == 2019]

df.head()

,Year,State,Average Median Age by County,Average Household Income by County,Average Per Capita Income by County,Total Population,Total Employed Civilians,Total Unemployed Civilians,Total People in the Military,Total Population in Poverty
156,2019,Alabama,40.801493,43574.850746,24049.149254,4876250,2097384.0,132095.0,13306.0,795989.0
157,2019,Alaska,37.279310,67789.344828,33072.896552,737068,347774.0,26808.0,17756.0,76933.0
158,2019,Arizona,40.626667,48989.933333,24500.266667,7050299,3130658.0,195905.0,19592.0,1043764.0
159,2019,Arkansas,41.610667,42236.706667,23285.040000,2999370,1303490.0,70481.0,4751.0,496260.0
160,2019,California,39.889655,67713.603448,33798.620690,39283497,18591241.0,1199233.0,131073.0,5149742.0

In [45]:
# Add a new column that calculates the Poverty Rate
df["Poverty Rate"] = round((df["Total Population in Poverty"] / df["Total Population"]), 2)

df.head()

,Year,State,Average Median Age by County,Average Household Income by County,Average Per Capita Income by County,Total Population,Total Employed Civilians,Total Unemployed Civilians,Total People in the Military,Total Population in Poverty,Poverty Rate
156,2019,Alabama,40.801493,43574.850746,24049.149254,4876250,2097384.0,132095.0,13306.0,795989.0,0.16
157,2019,Alaska,37.279310,67789.344828,33072.896552,737068,347774.0,26808.0,17756.0,76933.0,0.10
158,2019,Arizona,40.626667,48989.933333,24500.266667,7050299,3130658.0,195905.0,19592.0,1043764.0,0.15
159,2019,Arkansas,41.610667,42236.706667,23285.040000,2999370,1303490.0,70481.0,4751.0,496260.0,0.17
160,2019,California,39.889655,67713.603448,33798.620690,39283497,18591241.0,1199233.0,131073.0,5149742.0,0.13

In [ ]:
# Sort the data by Poverty Rate and Average Per Capita Income by County, Highest to Lowest
df = df.sort_values(by=["Poverty Rate", "Average Per Capita Income by County"], ascending=False)

# Reset Index
df.reset_index()

,index,Year,State,Average Median Age by County,Average Household Income by County,Average Per Capita Income by County,Total Population,Total Employed Civilians,Total Unemployed Civilians,Total People in the Military,Total Population in Poverty,Poverty Rate
0,195,2019,Puerto Rico,41.656410,19300.025641,11067.884615,3318447,1028513.0,196934.0,1845.0,1449091.0,0.44
1,180,2019,Mississippi,38.748780,39613.073171,21758.451220,2984418,1235224.0,99733.0,11721.0,585786.0,0.20
2,187,2019,New Mexico,41.739394,43722.969697,24620.212121,2092454,888646.0,63458.0,9895.0,392065.0,0.19
3,174,2019,Louisiana,38.053125,44874.015625,24386.296875,4664362,2033758.0,141020.0,17212.0,871467.0,0.19
4,205,2019,West Virginia,44.365455,44892.236364,24691.836364,1817305,740910.0,51910.0,1306.0,310044.0,0.17
5,173,2019,Kentucky,40.973333,44882.216667,24117.466667,4449052,1978477.0,116945.0,13747.0,747010.0,0.17
6,159,2019,Arkansas,41.610667,42236.706667,23285.040000,2999370,1303490.0,70481.0,4751.0,496260.0,0.17
7,156,2019,Alabama,40.801493,43574.850746,24049.149254,4876250,2097384.0,132095.0,13306.0,795989.0,0.16
8,164,2019,District of Columbia,34.000000,86420.000000,56147.000000,692683,376871.0,27967.0,3066.0,107140.0,0.15
9,199,2019,Tennessee,42.124211,47167.000000,25324.894737,6709356,3109872.0,172799.0,18830.0,996930.0,0.15
10,192,2019,Oklahoma,39.405195,48710.727273,25253.376623,3932870,1772123.0,94834.0,18971.0,598373.0,0.15
11,197,2019,South Carolina,41.432609,45608.326087,25193.478261,5020806,2275531.0,139526.0,32797.0,741650.0,0.15
12,158,2019,Arizona,40.626667,48989.933333,24500.266667,7050299,3130658.0,195905.0,19592.0,1043764.0,0.15
13,166,2019,Georgia,39.922013,47229.685535,24484.433962,10403847,4834622.0,290560.0,49356.0,1528558.0,0.15
14,188,2019,New York,41.632258,62484.612903,32578.419355,19572319,9498320.0,547509.0,23390.0,2681277.0,0.14
15,191,2019,Ohio,41.030682,55800.238636,28652.204545,11655397,5595444.0,314483.0,8544.0,1588343.0,0.14
16,178,2019,Michigan,44.780723,51808.349398,28080.843373,9965265,4654930.0,293894.0,4179.0,1398527.0,0.14
17,165,2019,Florida,43.761194,51290.223881,27563.283582,20901636,9495353.0,561448.0,59225.0,2870487.0,0.14
18,189,2019,North Carolina,42.721000,48419.490000,26640.940000,10264876,4764135.0,281344.0,94310.0,1467591.0,0.14
19,200,2019,Texas,39.235433,52847.590551,26280.503937,28260856,13253631.0,708827.0,93394.0,4072194.0,0.14
20,160,2019,California,39.889655,67713.603448,33798.620690,39283497,18591241.0,1199233.0,131073.0,5149742.0,0.13
21,184,2019,Nevada,43.958824,60119.647059,30188.705882,2972382,1406568.0,92426.0,8393.0,384690.0,0.13
22,193,2019,Oregon,43.944444,53953.111111,28958.138889,4129803,1979043.0,114559.0,3090.0,533527.0,0.13
23,182,2019,Montana,44.783929,50983.946429,28931.928571,1050649,512329.0,21513.0,3030.0,134605.0,0.13
24,198,2019,South Dakota,40.427273,54278.545455,28913.606061,870638,443891.0,15736.0,2663.0,110553.0,0.13
25,170,2019,Indiana,40.346739,55866.597826,28021.250000,6665703,3202509.0,161351.0,3661.0,867996.0,0.13
26,168,2019,Idaho,40.286364,50921.704545,25463.477273,1717750,792237.0,35879.0,4170.0,221256.0,0.13
27,181,2019,Missouri,41.502609,48096.113043,24973.565217,6104910,2916000.0,139789.0,18850.0,810045.0,0.13
28,196,2019,Rhode Island,43.080000,76114.400000,41684.000000,1057231,533878.0,30455.0,3593.0,125826.0,0.12
29,194,2019,Pennsylvania,43.344776,57056.089552,30052.686567,12791530,6199456.0,347378.0,6555.0,1539183.0,0.12
30,169,2019,Illinois,41.900000,56656.294118,29364.098039,12770631,6250862.0,394981.0,17674.0,1557873.0,0.12
31,172,2019,Kansas,41.390476,52864.685714,27615.295238,2910652,1440453.0,61002.0,18335.0,337739.0,0.12
32,163,2019,Delaware,41.900000,65988.000000,33956.000000,957248,455620.0,26481.0,3432.0,109400.0,0.11
33,202,2019,Vermont,44.992857,59759.785714,33184.500000,624313,329028.0,12323.0,581.0,65652.0,0.11
34,207,2019,Wyoming,40.443478,61828.652174,32161.782609,581024,288503.0,13544.0,2957.0,62257.0,0.11
35,206,2019,Wisconsin,43.656944,58305.861111,31034.361111,5790716,2982359.0,111564.0,3190.0,639160.0,0.11
36,204,2019,Washington,42.146154,59393.461538,30986.256410,7404107,3594279.0,187330.0,52871.0,785244.0,0.11
37,171,2019,Iowa,41.900000,57259.606061,30429.030303,3139508,1613902.0,62573.0,1666.0,348122.0,0.11
38,175,2019,Maine,46.462500,53568.750000,30126.562500,1335492,670417.0,28922.0,1931.0,153131.0,0.11
39,183,2019,Nebraska,43.216129,54695.021505,29498.569892,1914571,999212.0,34535.0,5751.0,206579.0,0.11
40,162,2019,Connecticut,41.825000,79201.375000,42480.500000,3575074,1815636.0,116456.0,8733.0,344146.0,0.10
41,177,2019,Massachusetts,41.928571,77745.571429,42183.071429,6850553,3612375.0,183355.0,5201.0,680962.0,0.10
42,186,2019,New Jersey,41.233333,82887.142857,42013.761905,8878503,4422491.0,258093.0,9265.0,869081.0,0.10
43,190,2019,North Dakota,42.847170,62475.396226,34891.849057,756717,402322.0,11406.0,6563.0,78198.0,0.10
44,157,2019,Alaska,37.279310,67789.344828,33072.896552,737068,347774.0,26808.0,17756.0,76933.0,0.10
45,161,2019,Colorado,42.471875,58794.796875,31972.546875,5610349,2904589.0,131371.0,33671.0,565873.0,0.10
46,203,2019,Virginia,42.136090,60756.736842,31250.180451,8454463,4156018.0,200850.0,120385.0,865691.0,0.10
47,201,2019,Utah,34.575862,63059.586207,26673.827586,3096848,1497354.0,55539.0,4322.0,298537.0,0.10
48,176,2019,Maryland,41.066667,77541.625000,38085.416667,6018848,3073886.0,164396.0,30952.0,539991.0,0.09
49,167,2019,Hawaii,44.360000,76428.600000,36972.000000,1422094,680258.0,30269.0,41537.0,130649.0,0.09
50,179,2019,Minnesota,41.880460,61656.482759,31850.701149,5563378,2958615.0,111115.0,2514.0,526065.0,0.09
51,185,2019,New Hampshire,44.540000,69308.200000,36819.600000,1348124,729701.0,27430.0,1950.0,98682.0,0.07

In [49]:
# Print out the data for the most poverty stricken state or territory
df.head(1)

,Year,State,Average Median Age by County,Average Household Income by County,Average Per Capita Income by County,Total Population,Total Employed Civilians,Total Unemployed Civilians,Total People in the Military,Total Population in Poverty,Poverty Rate
195,2019,Puerto Rico,41.65641,19300.025641,11067.884615,3318447,1028513.0,196934.0,1845.0,1449091.0,0.44

In [50]:
# Bonus: Print out the data for the least poverty sticken state or territory with one line of code
df.tail(1)

,Year,State,Average Median Age by County,Average Household Income by County,Average Per Capita Income by County,Total Population,Total Employed Civilians,Total Unemployed Civilians,Total People in the Military,Total Population in Poverty,Poverty Rate
185,2019,New Hampshire,44.54,69308.2,36819.6,1348124,729701.0,27430.0,1950.0,98682.0,0.07