In [12]:
# Import Dependencies
import pandas as pd

In [13]:
# DataFrame should have 3 columns: Frame, Price, and Sales AND 5 rows of data
art_gallery = [
    {"Frame": 1, "Price": 2, "Sales": 3},
    {"Frame": 4, "Price": 5, "Sales": 6},
    {"Frame": 7, "Price": 8, "Sales": 9},
    {"Frame": 10, "Price": 11, "Sales": 12},
    {"Frame": 13, "Price": 14, "Sales": 15}
]
art_gallery_df = pd.DataFrame(art_gallery)
art_gallery_df

   Frame  Price  Sales
0      1      2      3
1      4      5      6
2      7      8      9
3     10     11     12
4     13     14     15

In [14]:
# Use a different method of creating DataFrames to
# Create a DataFrame for an art gallery that contains three columns - "Painting", "Price", and "Popularity"
# and has 4 rows of data
art_gallery_2 = {
    "Painting": ["The Scream", "Mona Lisa", "Girl with a Pearl Earring", "The Starry Night", "The Persistence of Memory"],
    "Price": [500, 600, 700, 800, 900],
    "Popularity": ["Low", "High", "Medium", "High", "Low"]
}
art_gallery_2_df = pd.DataFrame(art_gallery_2)
art_gallery_2_df

                    Painting  Price Popularity
0                 The Scream    500        Low
1                  Mona Lisa    600       High
2  Girl with a Pearl Earring    700     Medium
3           The Starry Night    800       High
4  The Persistence of Memory    900        Low